### ISSUE TITLE
Find an Engine

### ISSUE THREAD

**Issue by DailyDoseOfAwesome** [KeepOurNetFree/nngme#4]
We need a game engine, someone suggested 2dlua.

**Comment by benjaminrsherman** [comment]
Possible ideas:
- [LÖVE (A graphics framework rather than a fully-fledged engine) (Lua)](https://love2d.org/)
- [Godot (Designed with a custom, python-esque language with support for C++ and C#)](https://godotengine.org/)
- [Defold (A bit more of an engine, but is closed-source) (Lua)](https://www.defold.com/)

I think that we should go with either LÖVE or Godot since they're both open-source.  While Godot has more features off the bat, I don't know if that level of complexity will be needed (although it has the benefit of C++ support).

**Comment by DailyDoseOfAwesome** [comment]
C++ support is always a bonus, especially if it has another easier language for main use.  Ideally though I think we should pick something that is simple enough to just "grab and go".  So something that is designed for creating games.  Think "Game maker" or something, but free.

**Comment by benjaminrsherman** [comment]
Godot is made for making games (LOVE is the bare-bones framework).  While obviously it won't be as versatile out of the box as an engine like Unity or Unreal, it should work for us.

**Comment by DailyDoseOfAwesome** [comment]
You decide, you've done more research into this.

**Comment by benjaminrsherman** [comment]
Having looked through the documentation for each, I say that we should use (LOVE)[https://love2d.org/].
